name: "Build"
on:
    push:
      branches:
        - main
    pull_request:

jobs:
  build:
    name: Build Job ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: ["11"]
    
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      
      - name: "Set up Java: ${{ matrix.java }}"
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: "adopt"

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Gradle build
        run: ./gradlew build
